AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-rspec

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 9

RSpec/MultipleExpectations:
  Max: 2
